"""
Donchian entry-quality audit (PLAN 11.56) — READ ONLY, changes nothing.

The observation that opened 11.56: entries are valid by rule but often go
negative almost immediately after fill, suggesting the signal buys
breakouts after the impulse is already crowded.

This tests that. Verdict from the 2026-08-10 run: **not supported.** Early
drawdown carries no information about the outcome, and no entry feature
separates winners from losers — which independently reproduces the
2026-07-12 profile already in the project's memory.

What it reports
---------------
1. Per-entry table: the fields 11.56 asks for — signal close, fill,
   fill-vs-signal, gap, volume spike, ATR%, extension over the breakout
   level, MFE/MAE at 1/3/5 sessions, exit reason, P&L, R.
2. Whether early adverse excursion predicts R.
3. Correlation of each entry feature with R.
3b. Correlation of context DURING the hold with R — the numbers the
   close-out rationale rests on, produced here rather than quoted from
   a one-off run.
4. A sweep of every candidate rule 11.56 names, against realised P&L.
5. The confound checks that make (4) readable.

Reading the sweep — IMPORTANT
-----------------------------
On the 2026-08-10 data **every** rule "improved" P&L. That is the
signature of optimising thresholds against 19 trades with a negative
baseline, not 10 separate edges. Two confounds are printed alongside it
and must be read with it:

* **Date.** The strongest rule (ATR% > 5) skips 53% of all entries, and 7
  of the 10 it skips are the single June pullback cohort. It selects a
  date range, not a feature. The overlap is printed, not asserted.
* **Sizing.** Dollar risk correlated +0.51 with ATR% under the pre-11.48
  inverse-risk-parity behaviour, so volatile names carried bigger
  positions *and* bigger losses. 11.48 fixed that, and only 1 of 19
  closed trades is post-fix — so almost the whole sample was generated by
  a regime that no longer exists.

Do not propose an entry filter from this script's output without trades
under the current configuration. Prior art: the 2026-07-12 profile
rejected an overextension veto because any threshold removing the
parabolic losers also removed the two biggest winners.

Data
----
Feed is IEX — the feed the engine actually traded on (CLAUDE.md replay
rule). Cache integrity is verified against Alpaca's calendar before any
replay, per 11.52 and the 11.54 counterfactual that returned nonsense
purely because a symbol's cache was missing a week.

**Two samples, kept apart.** ``closed_pnl`` is every trade with realised
P&L and is the sweep's baseline; ``closed_r`` is the subset with a usable
risk basis, so R exists. PWR 05-01 and WYFI 06-18 have null initial risk
fields — P&L but no R. Reusing the R-valid set for a P&L sweep silently
drops them and makes the printed baseline disagree with the trade count.
Every section labels which sample it used.

R is computed as ``pnl / (qty × initial_risk_per_share)``, NOT from
``initial_risk_dollars``. That column is stale on partially-filled
entries — it is written once at first fill and is preserve-first-non-null,
so a fill that completes later keeps the partial-based figure (2 of 24
rows on 2026-08-10: GOOG 05-11 and NOW 08-10).

Reproduce
---------
    venv/bin/python -m scripts.donchian_entry_audit
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from config import settings  # noqa: E402
from indicators.technicals import add_atr  # noqa: E402

REPLAY_FEED = "iex"
STRATEGY = "donchian_breakout"


# ── Pure helpers ────────────────────────────────────────────────────────────


def breakout_level(prior: pd.DataFrame, window: int = 30) -> float:
    """The N-day high the entry was supposed to break, EXCLUDING the signal bar.

    Including it makes the level equal that bar's own high, so every fill
    scores as "below the breakout" and the metric measures nothing. That
    error made extension look systematically negative on a first pass.
    """
    if len(prior) < window + 1:
        return float("nan")
    return float(prior["high"].iloc[-(window + 1):-1].max())


def excursions(
    bars: pd.DataFrame, entry_day: pd.Timestamp, fill: float, sessions: int
) -> tuple[float, float]:
    """(MFE, MAE) in percent over the entry session and the next N-1.

    Anchored on the fill, and starting at the entry session — the claim
    under test is about drawdown *immediately* after filling, so excluding
    the entry day would define the question away.
    """
    fwd = bars[bars.index >= entry_day].head(sessions)
    if fwd.empty:
        return float("nan"), float("nan")
    return (
        100 * (fwd["high"].max() - fill) / fill,
        100 * (fwd["low"].min() - fill) / fill,
    )


def exits_for_entry(
    exits: pd.DataFrame, entries: pd.DataFrame, symbol: str, entry_ts: str
) -> pd.DataFrame:
    """Sell rows belonging to one entry.

    A symbol can be traded repeatedly (QCOM, AAPL, AVGO, GOOG and AMZN all
    appear twice), so exits are bounded by the NEXT entry on the same
    symbol rather than taken as "everything after".
    """
    later = entries[(entries.symbol == symbol) & (entries.timestamp > entry_ts)]
    upper = later.timestamp.min() if len(later) else "9999"
    return exits[
        (exits.symbol == symbol)
        & (exits.timestamp > entry_ts)
        & (exits.timestamp < upper)
    ]


def filter_sweep(df: pd.DataFrame, rules: list[tuple[str, str, str, float]]) -> pd.DataFrame:
    """P&L of the trades each candidate rule would have KEPT.

    Returns one row per rule with the count kept/skipped and the delta
    against the unfiltered baseline. See the module docstring before
    reading any positive delta as an edge.
    """
    base = df.pnl.sum()
    out = []
    for col, label, op, thr in rules:
        mask = df[col] > thr if op == ">" else df[col] < thr
        kept = df[~mask]
        out.append(dict(
            rule=f"{label} {op} {thr}", kept=len(kept), skipped=int(mask.sum()),
            pnl_kept=round(kept.pnl.sum(), 0),
            delta=round(kept.pnl.sum() - base, 0),
            pct_skipped=round(100 * mask.mean(), 0),
        ))
    return pd.DataFrame(out).sort_values("delta", ascending=False)


# ── I/O ─────────────────────────────────────────────────────────────────────


def load_trades(db: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    con = sqlite3.connect(db)
    con.row_factory = sqlite3.Row
    try:
        entries = pd.DataFrame([dict(r) for r in con.execute(
            "SELECT timestamp,symbol,avg_fill_price,qty,order_type,"
            "initial_risk_per_share FROM trades "
            f"WHERE strategy='{STRATEGY}' AND side='buy' ORDER BY timestamp")])
        exits = pd.DataFrame([dict(r) for r in con.execute(
            "SELECT timestamp,symbol,qty,reason,realized_pnl FROM trades "
            f"WHERE strategy='{STRATEGY}' AND side='sell' ORDER BY timestamp")])
    finally:
        con.close()
    return entries, exits


def load_bars(symbols) -> dict[str, pd.DataFrame]:
    from data.fetcher import fetch_symbol

    out = {}
    for s in sorted(symbols):
        df, _ = fetch_symbol(
            s, start=datetime(2026, 1, 2, tzinfo=timezone.utc),
            end=datetime.now(timezone.utc), timeframe="1Day", feed=REPLAY_FEED,
        )
        df.index = pd.to_datetime(df.index).tz_localize(None).normalize()
        out[s] = df
    return out


def verify_cache(bars: dict[str, pd.DataFrame]) -> list[str]:
    """Interior holes against a REAL calendar — never another cached symbol."""
    from data import market_calendar

    problems = []
    for sym, df in bars.items():
        if df.empty:
            problems.append(f"{sym}: empty")
            continue
        missing = market_calendar.missing_sessions(
            df.index.min().date(), df.index.max().date(),
            {d.date() for d in df.index},
        )
        if missing is None:
            return ["CALENDAR UNAVAILABLE — integrity unverified, replay untrustworthy"]
        if missing:
            problems.append(f"{sym}: {len(missing)} interior hole(s)")
    return problems


def build(entries, exits, bars, spy=None) -> pd.DataFrame:
    rows = []
    for _, e in entries.iterrows():
        sym = e.symbol
        day = pd.Timestamp(datetime.fromisoformat(e.timestamp).date())
        bar = bars[sym]
        prior = bar[bar.index < day]
        if len(prior) < 35:
            continue
        fill = float(e.avg_fill_price)
        sig = float(prior["close"].iloc[-1])
        atr = float(add_atr(prior, settings.ATR_LENGTH)
                    [f"atr_{settings.ATR_LENGTH}"].iloc[-1])
        today = bar[bar.index == day]
        gap = (100 * (float(today["open"].iloc[0]) - sig) / sig
               if len(today) else np.nan)
        v20 = float(prior["volume"].tail(20).mean())
        volx = (float(today["volume"].iloc[0]) / v20
                if len(today) and v20 else np.nan)
        lvl = breakout_level(prior)
        mfe1, mae1 = excursions(bar, day, fill, 1)
        _, mae3 = excursions(bar, day, fill, 3)
        mfe5, mae5 = excursions(bar, day, fill, 5)

        ex = exits_for_entry(exits, entries, sym, e.timestamp)
        pnl = ex.realized_pnl.dropna().sum() if len(ex) else np.nan
        reason = (ex.sort_values("qty", ascending=False).reason.iloc[0]
                  if len(ex) else "OPEN")
        # Context during the hold. 11.56's close-out rationale rests on
        # these, so they are produced here rather than quoted from a
        # one-off run — a durable claim needs a reproducible source.
        hold_days, spy_ret, spy_dd = np.nan, np.nan, np.nan
        if len(ex) and ex.realized_pnl.notna().any():
            exit_day = pd.Timestamp(
                datetime.fromisoformat(ex.timestamp.iloc[-1]).date()
            )
            hold_days = (exit_day - day).days
            if spy is not None:
                w = spy[(spy.index >= day) & (spy.index <= exit_day)]
                if len(w):
                    spy_ret = 100 * (w["close"].iloc[-1] / w["close"].iloc[0] - 1)
                    spy_dd = 100 * (w["low"].min() / w["close"].iloc[0] - 1)
        rps = e.initial_risk_per_share
        risk = float(e.qty) * float(rps) if rps else np.nan
        r = pnl / risk if (risk and risk > 0 and pnl == pnl) else np.nan

        rows.append(dict(
            sym=sym, entry=e.timestamp[:10], type=str(e.order_type)[:6],
            fill=round(fill, 2), fill_vs_sig=round(100 * (fill - sig) / sig, 2),
            gap=round(gap, 2), vol_x=round(volx, 2),
            atr_pct=round(100 * atr / sig, 2),
            ext=round(100 * (fill - lvl) / lvl, 2) if lvl == lvl else np.nan,
            mae1=round(mae1, 2), mae3=round(mae3, 2), mae5=round(mae5, 2),
            mfe5=round(mfe5, 2), risk_d=round(risk, 0) if risk == risk else np.nan,
            hold_d=hold_days if hold_days == hold_days else np.nan,
            spy_ret=round(spy_ret, 2) if spy_ret == spy_ret else np.nan,
            spy_dd=round(spy_dd, 2) if spy_dd == spy_dd else np.nan,
            exit=str(reason)[:14],
            pnl=round(pnl, 0) if pnl == pnl else np.nan,
            R=round(r, 2) if r == r else np.nan,
        ))
    return pd.DataFrame(rows)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Donchian entry-quality audit (11.56)")
    ap.add_argument("--db", default="data/trades.db")
    args = ap.parse_args(argv)

    entries, exits = load_trades(args.db)
    if entries.empty:
        print("no Donchian entries found")
        return 0
    bars = load_bars(set(entries.symbol))

    print("=== cache integrity (Alpaca calendar, never a cached symbol) ===")
    problems = verify_cache(bars)
    print("  " + ("\n  ".join(problems) if problems else "clean"))
    if any("UNAVAILABLE" in p for p in problems):
        return 1

    spy = bars.get("SPY")
    if spy is None:
        spy = load_bars({"SPY"})["SPY"]
    df = build(entries, exits, bars, spy=spy)
    pd.set_option("display.width", 250)
    pd.set_option("display.max_columns", 40)
    print(f"\n=== {len(df)} Donchian entries ===\n")
    print(df.to_string(index=False))

    # TWO distinct samples, kept apart deliberately (review finding):
    #   closed_pnl — every trade with realised P&L. The sweep's baseline.
    #   closed_r   — the subset with a usable risk basis, so R exists.
    # PWR 05-01 and WYFI 06-18 have null initial risk fields, so they carry
    # P&L but no R. Reusing the R-valid set for a P&L sweep silently drops
    # them and makes the printed baseline disagree with the trade count.
    closed_pnl = df[df.pnl.notna()].copy()
    closed = df[df.R.notna()].copy()
    dropped = sorted(set(closed_pnl.sym) - set(closed.sym))
    print(f"\nclosed with P&L: {len(closed_pnl)}   "
          f"of which R-valid: {len(closed)}"
          + (f"   (no risk basis: {', '.join(dropped)})" if dropped else ""))
    if len(closed) < 5:
        print("\ntoo few closed trades to test anything")
        return 0

    print(f"\n=== does early drawdown predict R?  (R-valid, n={len(closed)}) ===\n")
    for c in ("mae1", "mae3", "mae5"):
        print(f"  corr({c}, R) = {closed[c].corr(closed.R):+.2f}")
    closed["bucket"] = np.where(closed.mae1 <= -2.0, "day-1 MAE <= -2%", "day-1 MAE > -2%")
    print()
    print(closed.groupby("bucket").agg(
        n=("R", "size"), win_pct=("R", lambda s: round(100 * (s > 0).mean(), 1)),
        mean_R=("R", "mean")).round(2).to_string())

    print(f"\n=== entry features vs R  (R-valid, n={len(closed)}) ===\n")
    for c in ("ext", "gap", "fill_vs_sig", "vol_x", "atr_pct"):
        print(f"  corr({c:12}, R) = {closed[c].corr(closed.R):+.2f}")

    print(f"\n=== context DURING the hold vs R  (R-valid, n={len(closed)}) ===\n")
    for c in ("hold_d", "spy_ret", "spy_dd"):
        if closed[c].notna().sum() > 4:
            print(f"  corr({c:8}, R) = {closed[c].corr(closed.R):+.2f}")
    print("  NB: these are outcomes/context, NOT entry levers — you cannot")
    print("      filter on how long a trade will last.")

    print(f"\n=== candidate rules vs realised P&L  (P&L-valid, n={len(closed_pnl)}) ===")
    print("    READ THE DOCSTRING: on this sample every rule 'improves'.\n")
    rules = [
        ("gap", "gap", ">", 2.0), ("gap", "gap", ">", 3.0), ("gap", "gap", "<", -3.0),
        ("fill_vs_sig", "chase", ">", 2.0), ("fill_vs_sig", "chase", ">", 5.0),
        ("ext", "extension", ">", 2.0), ("ext", "extension", ">", 5.0),
        ("atr_pct", "ATR%", ">", 5.0), ("atr_pct", "ATR%", ">", 6.0),
        ("vol_x", "volume x20d", "<", 1.0),
    ]
    print(f'    baseline total P&L = ${closed_pnl.pnl.sum():,.0f}\n')
    print(filter_sweep(closed_pnl, rules).to_string(index=False))

    print("\n=== confounds — read these WITH the sweep ===\n")
    hi = closed_pnl[closed_pnl.atr_pct > 5]
    lo = closed_pnl[closed_pnl.atr_pct <= 5]
    print(f"  corr(ATR%, risk dollars) = {closed.atr_pct.corr(closed.risk_d):+.2f}"
          "   <- pre-11.48 sizing scaled risk WITH volatility")
    if len(hi) and len(lo):
        print(f"  ATR%>5 : n={len(hi):2}  mean risk ${hi.risk_d.mean():5.0f}  "
              f"P&L ${hi.pnl.sum():+8,.0f}  wins {int((hi.R>0).sum())}")
        print(f"  ATR%<=5: n={len(lo):2}  mean risk ${lo.risk_d.mean():5.0f}  "
              f"P&L ${lo.pnl.sum():+8,.0f}  wins {int((lo.R>0).sum())}")
    jun_mask = ((closed_pnl.entry >= "2026-06-01") & (closed_pnl.entry <= "2026-06-30"))
    jun = closed_pnl[jun_mask]
    if len(hi):
        overlap = int(
            ((hi.entry >= "2026-06-01") & (hi.entry <= "2026-06-30")).sum()
        )
        print(f"  of the {len(hi)} trades ATR%>5 would skip, {overlap} are June "
              "— the rule selects a date range, not a feature")
    print(f"  June pullback cohort: {len(jun)} of {len(closed_pnl)} closed trades, "
          f"{int((jun.R > 0).sum())} winners")
    post = closed_pnl[closed_pnl.entry >= "2026-07-13"]
    print(f"  post-11.48 sizing:    {len(post)} of {len(closed_pnl)} closed trades")
    print("\n  A rule whose 'edge' lives in the June cohort is selecting a date,")
    print("  and one whose damage scaled with ATR was amplified by sizing 11.48 fixed.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
