"""
StrategyEnvelope — backtest-derived expected-behavior envelope per strategy.

The envelope provides the reference distribution the EdgeAssessor (11.10d)
compares live behavior against. It is the answer to "what does this
strategy look like when it's working correctly?"

v1 is **static** — generated by `scripts/build_envelopes.py` from a single
backtest run at production config. No auto-recalibration; no parameter-
grid distribution (both deferred to follow-up §F4 and §F5).

Design references:
  - design §7 Reference envelope
  - design §5 EdgeReport (consumes envelope's R-expectancy CI band)
  - design §6 L3 Drift (consumes envelope's lifecycle bands)
  - design §F1–F5 follow-ups (PSR/DSR/MinTRL, parameter-grid distribution,
    hybrid paper recalibration)

JSON shape (schema_version=1):
  - Edge metrics (R-expectancy primary, dollar secondary)
  - Behavior bands (trades_per_month, hold_days, p95 drawdown)
  - Lifecycle bands (raw_signals_per_week, block-rate ratios, fill rate) —
    nullable when the build script can't simulate the full gating pipeline.
    11.10g's calibration script can populate these from paper data later.

The envelope is operator-readable, git-friendly JSON. Edits to a strategy's
production config should regenerate the envelope (see 11.10a doc §15.1 Q6
on operator discipline).
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

ENVELOPE_SCHEMA_VERSION = 1


class FilterFidelity:
    """Machine-readable labels for how faithfully the build script's
    backtest reproduces production gating. Stored in
    `StrategyEnvelope.filter_fidelity` so the EdgeAssessor can decide
    how much trust to place in the envelope's trade-frequency /
    block-rate expectations.

    Hierarchy of "trust" (highest → lowest):
      PRODUCTION_FAITHFUL  — every live filter replayed per-bar with
                             correct historical state.
      PARTIAL_STOCK_GATES_ONLY — stock-level price/volume/SMA gates
                             replay correctly per-bar (the strategy's df
                             carries them); macro/live-cycle gates may
                             use build-time snapshots (SPY trend), and
                             optional gates like SectorMomentumFilter
                             are intentionally omitted. **This is the
                             v1 default for all equity envelopes.**
      RAW_NO_FILTERS       — strategy ran without any edge filter.
      NOT_BACKTESTED       — stub envelope (options strategies that
                             require live OPRA chains); filter fidelity
                             is not applicable.
      UNKNOWN              — default when not explicitly set; treat as
                             low-trust.

    Per the v1 invariant ("bot informs, operator decides"), the
    assessor consumes this label and adjusts its drift bands but
    never auto-disables a strategy on a low-fidelity envelope alone.
    """

    PRODUCTION_FAITHFUL = "production_faithful"
    PARTIAL_STOCK_GATES_ONLY = "partial_stock_gates_only"
    RAW_NO_FILTERS = "raw_no_filters"
    NOT_BACKTESTED = "not_backtested"
    UNKNOWN = "unknown"


def _normalize_non_finite(obj: object) -> object:
    """Recursively replace any non-finite float (NaN, +Inf, -Inf) with None.

    Walks dicts, lists, tuples. Used by `StrategyEnvelope.to_json` to
    keep envelope JSON standard-compliant. Build script catches
    non-finite at construction time but this is defense-in-depth.
    """
    if isinstance(obj, float):
        return None if not math.isfinite(obj) else obj
    if isinstance(obj, dict):
        return {k: _normalize_non_finite(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return type(obj)(_normalize_non_finite(v) for v in obj)
    return obj


@dataclass(frozen=True)
class StrategyEnvelope:
    """Expected-behavior envelope for one strategy at one config snapshot.

    `risk_unit_dollars` is the dollar value of 1R used to compute R metrics
    in this envelope. The EdgeAssessor must use the same unit when
    comparing live R-expectancy. v1 formula:
        risk_unit_dollars = initial_cash * approx_stop_pct
    (vectorbt sizes positions all-in, so position notional ≈ initial_cash.)
    Documented in the envelope so apples-to-apples comparison is auditable.

    `filter_fidelity` is a structured tag the assessor reads programmatically
    to know how closely the envelope reflects live production gating. See
    `FilterFidelity` for values. A `partial_stock_gates_only` envelope is
    expected to over-report trade frequency vs production (live filters
    reject more signals); the assessor should widen its drift confidence
    bands accordingly.

    Tuples are used instead of lists for frozen-collection immutability.
    Optional fields (lifecycle bands, R metrics) are nullable so the build
    script can tolerate partial coverage.
    """

    schema_version: int
    strategy: str
    built_at: str  # ISO8601 timestamp
    backtest_window_start: str  # ISO date
    backtest_window_end: str
    backtest_config: dict[str, Any] = field(default_factory=dict)
    # PR #17 reviewer feedback: explicit machine-readable label for how
    # faithfully the backtest filters replay production. v1 envelopes ship
    # as "partial_stock_gates_only" — see FilterFidelity values for the
    # precise semantics.
    filter_fidelity: str = "unknown"

    # ── Edge metrics (R-expectancy is primary; dollar secondary) ──
    r_expectancy: float | None = None
    r_expectancy_ci_95: tuple[float, float] | None = None
    risk_unit_dollars: float | None = None
    expectancy_dollars: float | None = None
    expectancy_dollars_ci_95: tuple[float, float] | None = None
    win_rate: float | None = None
    win_rate_ci_95: tuple[float, float] | None = None
    profit_factor: float | None = None
    profit_factor_ci_95: tuple[float, float] | None = None
    sharpe: float | None = None
    cagr: float | None = None
    trade_count: int = 0

    # ── Behavior bands (p10, p90) ─────────────────────────────────
    trades_per_month_band: tuple[float, float] | None = None
    hold_days_band: tuple[float, float] | None = None
    p95_drawdown_pct: float | None = None

    # ── Lifecycle bands (consumed by L3 Drift) ────────────────────
    # All nullable. The build script ships these as null when the
    # gating pipeline can't be simulated cleanly; the calibration
    # script (11.10g) populates them from paper data later.
    raw_signals_per_week_band: tuple[float, float] | None = None
    edge_filter_block_rate_band: tuple[float, float] | None = None
    regime_block_rate_band: tuple[float, float] | None = None
    risk_block_rate_band: tuple[float, float] | None = None
    submitted_per_raw_signal_band: tuple[float, float] | None = None
    fill_rate_band: tuple[float, float] | None = None

    # ── Build-time annotations (for the operator) ─────────────────
    # Free-form notes captured by the build script — e.g.
    # "lifecycle bands skipped: spy_options_reversion requires live
    # OPRA quotes, not feasible offline."
    notes: tuple[str, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        # Coerce list inputs to tuples for frozen semantics.
        for fname in ("notes",):
            current = getattr(self, fname)
            if not isinstance(current, tuple):
                object.__setattr__(self, fname, tuple(current))

    def to_json(self) -> str:
        """Pretty-printed JSON, suitable for committing to git.

        Defensive: any non-finite float (NaN/Inf) anywhere in the
        envelope is replaced with None before encoding. Standard JSON
        has no representation for Infinity — strict parsers (jq,
        browser JSON.parse) reject the `Infinity` token Python's
        default encoder emits. `allow_nan=False` is set as a final
        backstop so an accidental Infinity raises here rather than
        silently producing non-compliant output.

        Build script (scripts/build_envelopes.py) catches non-finite at
        construction time and appends an explanatory note; this layer
        is just defense in depth.
        """

        def _default(obj: object) -> object:
            if isinstance(obj, date):
                return obj.isoformat()
            if isinstance(obj, tuple):
                return list(obj)
            raise TypeError(f"unserializable: {type(obj).__name__}")

        data = _normalize_non_finite(asdict(self))
        return json.dumps(data, default=_default, indent=2, allow_nan=False)

    def write(self, path: str | Path) -> None:
        """Atomic write — tmp file + os.replace, mirrors the engine's
        state-snapshot pattern (engine/trader.py:2957)."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(self.to_json())
        tmp.replace(path)

    @classmethod
    def from_json(cls, text: str) -> "StrategyEnvelope":
        """Inverse of `to_json`. Tuples are restored from JSON lists.

        Forward-compat: unknown fields are silently ignored so a newer
        envelope file can be read by an older bot version (with the new
        fields treated as missing).
        """
        data = json.loads(text)
        return cls._from_dict(data)

    @classmethod
    def read(cls, path: str | Path) -> "StrategyEnvelope":
        return cls.from_json(Path(path).read_text())

    @classmethod
    def _from_dict(cls, data: dict[str, Any]) -> "StrategyEnvelope":
        # Restore tuples for the typed fields.
        def _tuple_or_none(v: object) -> tuple[float, float] | None:
            if v is None:
                return None
            return (float(v[0]), float(v[1]))

        # Filter to known fields for forward-compat.
        known = {f.name for f in cls.__dataclass_fields__.values()}
        filtered = {k: v for k, v in data.items() if k in known}

        # Coerce CI tuples
        for fname in (
            "r_expectancy_ci_95",
            "expectancy_dollars_ci_95",
            "win_rate_ci_95",
            "profit_factor_ci_95",
            "trades_per_month_band",
            "hold_days_band",
            "raw_signals_per_week_band",
            "edge_filter_block_rate_band",
            "regime_block_rate_band",
            "risk_block_rate_band",
            "submitted_per_raw_signal_band",
            "fill_rate_band",
        ):
            if fname in filtered:
                filtered[fname] = _tuple_or_none(filtered[fname])

        # Coerce notes to tuple (handled by __post_init__ too)
        if "notes" in filtered and filtered["notes"] is not None:
            filtered["notes"] = tuple(filtered["notes"])

        return cls(**filtered)


def envelope_path(strategy: str, *, root: str | Path | None = None) -> Path:
    """Standard on-disk path for a strategy's envelope JSON.

    Defaults to `data/envelopes/{strategy}.json` relative to the project
    root. `root` override is used in tests + scripts that want to write
    to a tmp location.
    """
    if root is None:
        root = Path(__file__).resolve().parents[2] / "data" / "envelopes"
    return Path(root) / f"{strategy}.json"
